/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const NosotrosIndexLazyImport = createFileRoute('/nosotros/')()
const MenuIndexLazyImport = createFileRoute('/menu/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const NosotrosIndexLazyRoute = NosotrosIndexLazyImport.update({
  path: '/nosotros/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/nosotros/index.lazy').then((d) => d.Route),
)

const MenuIndexLazyRoute = MenuIndexLazyImport.update({
  path: '/menu/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/menu/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/menu/': {
      preLoaderRoute: typeof MenuIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/nosotros/': {
      preLoaderRoute: typeof NosotrosIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  MenuIndexLazyRoute,
  NosotrosIndexLazyRoute,
])

/* prettier-ignore-end */
